apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: patientservice-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: patientservice-db
  labels:
    app: patientService-db
    service: patientservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patientService-db
      service: patientservice
  template:
    metadata:
      labels:
        app: patientService-db
        service: patientservice
    spec:
      serviceAccountName: patientservice-db
      volumes:
      - name: patientservice-db-volume
        persistentVolumeClaim:
          claimName: patientservice-db
      containers:
      - name: patientservice-db-container
        image: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: "/var/lib/postgresql"
          name: patientservice-db-volume
        env: 
        - name: POSTGRES_USER
          value: "admin_user"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "patient-service-db"