apiVersion: v1
kind: Service
metadata:
  name: patientservice-db
  labels:
    app: patientService-db
    service: patientservice
spec:
  selector:
    app: patientService-db
    service: patientservice
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP