apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: patientservice

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: patientservice
  labels:
    app: patientService
    service: patientservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patientService
      service: patientservice
  template:
    metadata:
      labels:
        app: patientService
        service: patientservice
    spec:
      serviceAccountName: patientservice
      
      containers:
      - name: patientservice-container
        image: hhana982/patientservice:1.<version>
        ports:
        - containerPort: 8080
        
        env: 
          - name: DB_USER
            value: "admin_user"
          - name: DB_PASSWORD
            value: "password"
          - name: DB_NAME
            value: "patient-service-db"