apiVersion: v1
kind: Service
metadata:
  name: patientservice
  labels:
    app: patientService
    service: patientservice
spec:
  selector:
    app: patientService
    service: patientservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP